// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRdCK7GH6r2RO_6jfDoHhn9uJ-CxCsisM',
    appId: '1:128461901982:web:184947002f1cc6a0c32b8f',
    messagingSenderId: '128461901982',
    projectId: 'astroapp-ce344',
    authDomain: 'astroapp-ce344.firebaseapp.com',
    storageBucket: 'astroapp-ce344.firebasestorage.app',
    //storageBucket: 'astroapp-ce344.appspot.com',
    measurementId: 'G-3PKBGXFXXD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ5yYun14xeVMVIlS5f8HcwkfbHQcj-9Q',
    appId: '1:128461901982:android:305bfaae3ea79413c32b8f',
    messagingSenderId: '128461901982',
    projectId: 'astroapp-ce344',
    storageBucket: 'astroapp-ce344.firebasestorage.app',
    //storageBucket: 'astroapp-ce344.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwDRpklHvgjbnDvFS8P2v2VXcfzw2TUuQ',
    appId: '1:128461901982:ios:adeacc8604ca7bdac32b8f',
    messagingSenderId: '128461901982',
    projectId: 'astroapp-ce344',
    storageBucket: 'astroapp-ce344.firebasestorage.app',
    //storageBucket: 'astroapp-ce344.appspot.com',
    iosBundleId: 'com.example.astronomyApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwDRpklHvgjbnDvFS8P2v2VXcfzw2TUuQ',
    appId: '1:128461901982:ios:adeacc8604ca7bdac32b8f',
    messagingSenderId: '128461901982',
    projectId: 'astroapp-ce344',
    storageBucket: 'astroapp-ce344.firebasestorage.app',
    //storageBucket: 'astroapp-ce344.appspot.com',
    iosBundleId: 'com.example.astronomyApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRdCK7GH6r2RO_6jfDoHhn9uJ-CxCsisM',
    appId: '1:128461901982:web:e5f506fef99f6036c32b8f',
    messagingSenderId: '128461901982',
    projectId: 'astroapp-ce344',
    authDomain: 'astroapp-ce344.firebaseapp.com',
    storageBucket: 'astroapp-ce344.firebasestorage.app',
    //storageBucket: 'astroapp-ce344.appspot.com',
    measurementId: 'G-SVTTY3NLMY',
  );

}